apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    tier: frontend
spec:
  containers:
    - image: prit
      imagePullPolicy: Never
      name: nodewebapp
      ports:
        - containerPort: 3040
  dnsPolicy: ClusterFirst
  restartPolicy: Always
